version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "HelloSAMApp"
s3_bucket = "sam-deployment-bucket-ausard"
region = "eu-central-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
parameter_overrides = "StageName=\"dev\""

